/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "AdmobAds_autodefs.h"
#include "s3eEdk.h"
#include "AdmobAds.h"
//Declarations of Init and Term functions
extern s3eResult AdmobAdsInit();
extern void AdmobAdsTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static s3eResult InitAds_wrap(const char* pub_id)
{
    IwTrace(ADMOBADS_VERBOSE, ("calling AdmobAds func on main thread: InitAds"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)InitAds, 1, pub_id);
}

static s3eResult ShowAds_wrap()
{
    IwTrace(ADMOBADS_VERBOSE, ("calling AdmobAds func on main thread: ShowAds"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ShowAds, 0);
}

static s3eResult HideAds_wrap()
{
    IwTrace(ADMOBADS_VERBOSE, ("calling AdmobAds func on main thread: HideAds"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)HideAds, 0);
}

static bool hasAdLoaded_wrap()
{
    IwTrace(ADMOBADS_VERBOSE, ("calling AdmobAds func on main thread: hasAdLoaded"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)hasAdLoaded, 0);
}

#define InitAds InitAds_wrap
#define ShowAds ShowAds_wrap
#define HideAds HideAds_wrap
#define hasAdLoaded hasAdLoaded_wrap

#endif

void AdmobAdsRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[4];
    funcPtrs[0] = (void*)InitAds;
    funcPtrs[1] = (void*)ShowAds;
    funcPtrs[2] = (void*)HideAds;
    funcPtrs[3] = (void*)hasAdLoaded;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[4] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("AdmobAds", funcPtrs, sizeof(funcPtrs), flags, AdmobAdsInit, AdmobAdsTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int AdmobAdsStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&AdmobAdsRegisterExt;
    return 0;
}

int g_AdmobAdsVal = AdmobAdsStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    AdmobAdsRegisterExt();
}
#endif

#endif
